"""fase 6: stripe_customer_id

Revision ID: 37d54ba648cf
Revises: fbbba5d499a9
Create Date: 2026-07-24 18:48:35.319021
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '37d54ba648cf'
down_revision: str | None = 'fbbba5d499a9'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'stripe_customer_id')
    # ### end Alembic commands ###
