"""fase 2: schema dati completo

Revision ID: fbbba5d499a9
Revises: 11b0aca5b281
Create Date: 2026-07-22 20:50:15.340274
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "fbbba5d499a9"
down_revision: str | None = "11b0aca5b281"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "nis2_category",
            sa.Enum("essenziale", "importante", "non_in_perimetro", name="nis2_category"),
            nullable=False,
        ),
        sa.Column("cra_in_scope", sa.Boolean(), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assessment_results_org_created",
        "assessment_results",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_results_organization_id"),
        "assessment_results",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "compliance_measures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("measure_id", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "conforme", "parziale", "non_conforme", "non_applicabile", name="measure_status"
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "measure_id", name="uq_compliance_measure_per_org"),
    )
    op.create_index(
        "ix_compliance_measures_org_updated",
        "compliance_measures",
        ["organization_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_measures_organization_id"),
        "compliance_measures",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum(
                "registro_rischi",
                "procedura_incident_response",
                "piano_bcp",
                "politica_supply_chain",
                "politica_crittografia",
                "politica_controllo_accessi",
                "procedura_vulnerability_disclosure",
                "piano_formazione",
                "registro_asset_critici",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pdf_url", sa.String(length=1024), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_documents_org_created", "documents", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_documents_organization_id"), "documents", ["organization_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("incident_type", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("aperto", "in_gestione", "chiuso", name="incident_status"),
            nullable=False,
        ),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_incidents_org_opened", "incidents", ["organization_id", "opened_at"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_organization_id"), "incidents", ["organization_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("free", "essential", "business", "enterprise", name="subscription_plan"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("trialing", "active", "past_due", "canceled", name="subscription_status"),
            nullable=False,
        ),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("renews_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_organization_id"), "subscriptions", ["organization_id"], unique=True
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column(
            "criticality",
            sa.Enum("alta", "media", "bassa", name="supplier_criticality"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("conforme", "parziale", "non_conforme", "non_valutato", name="supplier_status"),
            nullable=False,
        ),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_suppliers_org_status", "suppliers", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_suppliers_organization_id"), "suppliers", ["organization_id"], unique=False
    )
    op.create_table(
        "incident_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum(
                "early_warning_24h",
                "notifica_72h",
                "relazione_30gg",
                "cra_enisa_24h",
                "cra_enisa_72h",
                name="notification_phase",
            ),
            nullable=False,
        ),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_notifications_incident_id"),
        "incident_notifications",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "supplier_questionnaires",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_status",
            sa.Enum("conforme", "parziale", "non_conforme", "non_valutato", name="supplier_status"),
            nullable=False,
        ),
        sa.Column("access_token", sa.String(length=128), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
    )
    op.create_index(
        op.f("ix_supplier_questionnaires_supplier_id"),
        "supplier_questionnaires",
        ["supplier_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_supplier_questionnaires_supplier_id"), table_name="supplier_questionnaires"
    )
    op.drop_table("supplier_questionnaires")
    op.drop_index(
        op.f("ix_incident_notifications_incident_id"), table_name="incident_notifications"
    )
    op.drop_table("incident_notifications")
    op.drop_index(op.f("ix_suppliers_organization_id"), table_name="suppliers")
    op.drop_index("ix_suppliers_org_status", table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_subscriptions_organization_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_incidents_organization_id"), table_name="incidents")
    op.drop_index("ix_incidents_org_opened", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_documents_organization_id"), table_name="documents")
    op.drop_index("ix_documents_org_created", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_compliance_measures_organization_id"), table_name="compliance_measures")
    op.drop_index("ix_compliance_measures_org_updated", table_name="compliance_measures")
    op.drop_table("compliance_measures")
    op.drop_index(op.f("ix_assessment_results_organization_id"), table_name="assessment_results")
    op.drop_index("ix_assessment_results_org_created", table_name="assessment_results")
    op.drop_table("assessment_results")
    # ### end Alembic commands ###
